package aula;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.image.BufferStrategy;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/*
 * FrmJogo.java
 *
 * Created on 7 de Mar�o de 2007, 19:52
 */

/**
 *
 * @author  Glauco
 */
public class FrmJogo extends javax.swing.JFrame implements Runnable {
    
    /** Controle do teclado */
    private boolean esquerdaPressed    = false;
    private boolean direitaPressed     = false;
    
    /** Creates new form FrmJogo */
    public FrmJogo() {
        
        initComponents();
        
        createBufferStrategy(2);
        
        Thread t = new Thread(this);
        
        t.start();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 819, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 467, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased

        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            esquerdaPressed = false;
        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            direitaPressed = false;
        }
    }//GEN-LAST:event_formKeyReleased
        
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

        if (evt.getKeyCode() == KeyEvent.VK_LEFT) {
            esquerdaPressed = true;
        }
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT) {
            direitaPressed = true;
        }
    }//GEN-LAST:event_formKeyPressed
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmJogo().setVisible(true);
            }
        });
    }
    
    @Override
    public void run() {
        Game game = new Game(getWidth(), getHeight());
   
        while (true) {
            Graphics g = getBufferStrategy().getDrawGraphics();
            BufferStrategy buffer = getBufferStrategy();

            g.setFont(new Font("Dialog", Font.ITALIC, 25));
            
            game.update(g);
            game.updateScore(g);
            game.setPlayerActions(direitaPressed, esquerdaPressed);
            
            g.dispose();
            buffer.show();

            try {
                Thread.sleep(10);
            } catch (InterruptedException ex) {

            }
        }   
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

} 






















